"""
Shared defaults for MPro GINE models and matching PyG Explainer task config.
"""

from mprov3_gine_explainer_defaults.explainer_algorithm_defaults import (
    DEFAULT_GNN_EXPLAINER_EPOCHS,
    DEFAULT_GNN_EXPLAINER_LR,
    DEFAULT_IG_INTERNAL_BATCH_SIZE,
    DEFAULT_IG_N_STEPS,
    DEFAULT_PG_EXPLAINER_EPOCHS,
    DEFAULT_PG_EXPLAINER_LR,
    DEFAULT_PGM_NUM_SAMPLES,
)
from mprov3_gine_explainer_defaults.gine_architecture import (
    DEFAULT_DROPOUT,
    DEFAULT_EDGE_DIM,
    DEFAULT_HIDDEN_CHANNELS,
    DEFAULT_IN_CHANNELS,
    DEFAULT_NUM_LAYERS,
    DEFAULT_OUT_CLASSES,
    DEFAULT_POOL,
)
from mprov3_gine_explainer_defaults.pyg_explainer import DEFAULT_EXPLANATION_TYPE, DEFAULT_MODEL_CONFIG, PHENOMENON_EXPLANATION_TYPE
from mprov3_gine_explainer_defaults.pyg_mask_types import EDGE_MASK_OBJECT, NODE_MASK_ATTRIBUTES
from mprov3_gine_explainer_defaults.training_defaults import (
    DEFAULT_BATCH_SIZE,
    DEFAULT_FOLD_INDEX,
    DEFAULT_NUM_FOLDS,
    DEFAULT_SEED,
    DEFAULT_TRAINING_EPOCHS,
    DEFAULT_TRAINING_LR,
)
from mprov3_gine_explainer_defaults.best_fold import (
    FoldMetric,
    read_num_folds_for_fold,
    resolve_best_fold_index,
)
from mprov3_gine_explainer_defaults.fold_indices import resolve_fold_indices
from mprov3_gine_explainer_defaults.results_path_resolution import (
    explanations_run_dir,
    resolve_checkpoint_path,
    resolve_dataset_dir,
    resolve_training_checkpoint_and_dataset_name,
    training_checkpoint_path,
    visualizations_run_dir,
)
from mprov3_gine_explainer_defaults.gine_project_paths import (
    DEFAULT_DATA_ROOT,
    DEFAULT_RESULTS_ROOT,
    GINE_PROJECT_DIR,
    MPRO_EXPLAINER_PROJECT_DIR,
    WORKSPACE_ROOT,
)
from mprov3_gine_explainer_defaults.split_config import SplitConfig
from mprov3_gine_explainer_defaults.data_path_defaults import (
    BUILT_DATASET_FOLDER_NAME,
    CHECK_FORMAT_DATASETS_SUBDIR,
    CHECK_FORMAT_RAW_DATA_SUBDIR,
    CLASSIFICATION_RESULTS_JSON,
    DEFAULT_MPRO_SNAPSHOT_DIR_NAME,
    DEFAULT_PYG_DATASET_NAME,
    DEFAULT_TEST_SPLIT_FILE,
    DEFAULT_TRAIN_SPLIT_FILE,
    DEFAULT_TRAINING_CHECKPOINT_FILENAME,
    DEFAULT_VAL_SPLIT_FILE,
    LEGACY_EVALUATION_RESULTS_JSON,
    MPRO_INFO_CSV,
    MPRO_LIGAND_DIR,
    MPRO_LIGAND_SDF_SUBDIR,
    MPRO_SPLITS_DIR,
    PYG_DATA_FILENAME,
    PYG_PDB_ORDER_FILENAME,
    RESULTS_CHECK_FORMAT,
    RESULTS_CLASSIFICATIONS,
    RESULTS_DATASETS,
    RESULTS_DIR_NAME,
    RESULTS_EXPLANATIONS,
    RESULTS_TRAININGS,
    RESULTS_VISUALIZATIONS,
)

__all__ = [
    "SplitConfig",
    "WORKSPACE_ROOT",
    "GINE_PROJECT_DIR",
    "MPRO_EXPLAINER_PROJECT_DIR",
    "DEFAULT_DATA_ROOT",
    "DEFAULT_RESULTS_ROOT",
    "DEFAULT_IN_CHANNELS",
    "DEFAULT_HIDDEN_CHANNELS",
    "DEFAULT_NUM_LAYERS",
    "DEFAULT_DROPOUT",
    "DEFAULT_OUT_CLASSES",
    "DEFAULT_POOL",
    "DEFAULT_EDGE_DIM",
    "DEFAULT_EXPLANATION_TYPE",
    "DEFAULT_MODEL_CONFIG",
    "PHENOMENON_EXPLANATION_TYPE",
    "NODE_MASK_ATTRIBUTES",
    "EDGE_MASK_OBJECT",
    "DEFAULT_GNN_EXPLAINER_EPOCHS",
    "DEFAULT_GNN_EXPLAINER_LR",
    "DEFAULT_PG_EXPLAINER_EPOCHS",
    "DEFAULT_PG_EXPLAINER_LR",
    "DEFAULT_IG_N_STEPS",
    "DEFAULT_IG_INTERNAL_BATCH_SIZE",
    "DEFAULT_PGM_NUM_SAMPLES",
    "DEFAULT_TRAINING_EPOCHS",
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_TRAINING_LR",
    "DEFAULT_SEED",
    "DEFAULT_NUM_FOLDS",
    "DEFAULT_FOLD_INDEX",
    "DEFAULT_MPRO_SNAPSHOT_DIR_NAME",
    "MPRO_INFO_CSV",
    "MPRO_SPLITS_DIR",
    "MPRO_LIGAND_DIR",
    "MPRO_LIGAND_SDF_SUBDIR",
    "DEFAULT_TRAIN_SPLIT_FILE",
    "DEFAULT_VAL_SPLIT_FILE",
    "DEFAULT_TEST_SPLIT_FILE",
    "RESULTS_DIR_NAME",
    "RESULTS_TRAININGS",
    "RESULTS_DATASETS",
    "RESULTS_CLASSIFICATIONS",
    "RESULTS_VISUALIZATIONS",
    "RESULTS_EXPLANATIONS",
    "RESULTS_CHECK_FORMAT",
    "CHECK_FORMAT_DATASETS_SUBDIR",
    "CHECK_FORMAT_RAW_DATA_SUBDIR",
    "PYG_DATA_FILENAME",
    "PYG_PDB_ORDER_FILENAME",
    "DEFAULT_TRAINING_CHECKPOINT_FILENAME",
    "DEFAULT_PYG_DATASET_NAME",
    "BUILT_DATASET_FOLDER_NAME",
    "CLASSIFICATION_RESULTS_JSON",
    "LEGACY_EVALUATION_RESULTS_JSON",
    "FoldMetric",
    "read_num_folds_for_fold",
    "resolve_best_fold_index",
    "resolve_fold_indices",
    "resolve_checkpoint_path",
    "training_checkpoint_path",
    "resolve_dataset_dir",
    "resolve_training_checkpoint_and_dataset_name",
    "explanations_run_dir",
    "visualizations_run_dir",
]
